# Generated by Django 5.2.5 on 2025-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='role',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('entidad', 'Entidad Gubernamental'), ('admin', 'Administrador')], default='ciudadano', max_length=20),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('santa ana centro', 'Santa Ana Centro'), ('santa ana oeste', 'Santa Ana Oeste')], max_length=100, null=True),
        ),
    ]
