# Generated by Django 5.2.5 on 2025-09-07 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reporte', models.CharField(max_length=200)),
                ('descripcion_reporte', models.CharField(max_length=500)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado_reporte', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('reparado', 'Reparado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
