# Generated by Django 5.2.5 on 2025-09-12 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_rename_reporte_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reporte', models.CharField(max_length=200)),
                ('descripcion_reporte', models.CharField(max_length=500)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado_reporte', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('reparado', 'Reparado')], default='pendiente', max_length=20)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
