# Generated by Django 5.2.5 on 2025-09-13 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_create_entidad_group'),
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'permissions': [('can_change_status', 'Can change report status')]},
        ),
        migrations.AddField(
            model_name='reporte',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.ciudad'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='entidad_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
