# Generated by Django 5.2.5 on 2025-09-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporte_options_reporte_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
