# Generated by Django 5.2.5 on 2025-09-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_reporte_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='image',
            new_name='imagen',
        ),
    ]
